/*

 * Author: Automatic generated by WINOLOGY.
 * Title:  rating.backup

 Description:
 Backup file of ratings DB, automatic generated by WINOLOGY.
*/

rating(rating_0,[time=breakfast,food=cereals,person=chiara,wine=moscatoDAsti]).
rating(rating_0,[time=breakfast,food=cereals,person=chiara,wine=proseccoTerreNardinVenti2]).
rating(rating_1,[time=breakfast,food=fish,person=chiara,wine=moscatoDAsti]).
rating(rating_2,[time=lunch,food=fish,person=chiara,wine=primitivoDiManduria]).
rating(rating_3,[time=aperitivo,food=aperitivo,person=chiara,wine=primitivoDiManduria]).
rating(rating_3,[time=aperitivo,food=aperitivo,person=chiara,wine=vernacciaSerrapetrona]).
rating(rating_4,[time=dinner,food=dinner,person=chiara,wine=primitivoDiManduria]).
rating(rating_5,[time=lunch,food=fish,person=chiara,wine=luganaSanti]).
rating(rating_5,[time=dinner,food=dessert,person=chiara,wine=vernacciaSerrapetrona]).
rating(rating_5,[time=lunch,food=meat,person=chiara,wine=fragolinoTerreDelSole]).
rating(rating_5,[time=dinner,food=pizza,person=chiara,wine=fragolinoTerreDelSole]).
