/*

 * Author: Automatic generated by WINOLOGY.
 * Title:  wine.backup

 Description:
 Backup file of wines DB, automatic generated by WINOLOGY.
 */
wineObj(fragolinoTerreDelSole,[aroma=fruity,body=light_bodied,color=red,effervescence=no,sweetness=sweet]).
wineObj(proseccoTerreNardinVenti2,[aroma=aromatic,body=light_bodied,color=yellow,effervescence=yes,sweetness=dry]).
wineObj(moscatoDAsti,[aroma=aromatic,body=light_bodied,color=yellow,effervescence=yes,sweetness=off_dry]).
wineObj(verdicchioDiMatelica,[aroma=fruity,body=medium_bodied,color=yellow,effervescence=no,sweetness=off_dry]).
wineObj(vernacciaSerrapetrona,[aroma=aromatic,body=medium_bodied,color=red,effervescence=no,sweetness=sweet]).
wineObj(primitivoDiManduria,[aroma=aromatic,body=full_bodied,color=red,effervescence=no,sweetness=off_dry]).
wineObj(luganaSanti,[aroma=floreal,body=light_bodies,color=yellow,effervescence=yes,sweetnees=sweet]).
